[package]
name = "net-stalker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.98"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [ "std", "env-filter", "chrono" ] }
tokio = { version = "1.45.0", features = ["full"] }
ctrlc = {  version = "3.4.7", features = ["termination"] }
reqwest = { version = "0.12.15" }
axum = "0.8.4"
scraper = "0.23.1"
rss = { version = "2.0.12", features = ["builders", "atom"] }
chrono = "0.4.41"
chrono-tz = "0.10.3"
urlencoding = "2.1.3"
url = "2.5.4"
