[package]
name = "kouan-rss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
log = "0.4.16"
env_logger = "0"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11" }
axum = "0"
scraper = "0.13.0"
rss = { version = "2", features = ["builders", "atom"] }
sha2 = "0"
