---
version: '3.9'
services:
  web:
    image: 'rss-feed_web'
    build:
      context: '.'
    container_name: 'rss-feed_web'
    hostname: 'rss-feed_web'
    user: "${UID}:${GID}"
    environment:
#      - 'LDFLAGS=-Wl,-z,stack-size=16777216' #16MB
      - 'RUST_LOG=INFO'
    restart: always
    expose:
      - '3000'
    networks:
      - 'planet-link'

networks:
  planet-link:
    external: true
